packages:
  - "apps/*"
  - "packages/*"


catalog:
  "@t3-oss/env-nextjs": "0.12.0"
  "@tailwindcss/postcss": "4.1.8"
  "@tanstack/react-query": "5.66.9"
  "@trpc/client": "11.3.1"
  "@trpc/server": "11.3.1"
  "@trpc/tanstack-react-query": "11.3.1"
  "@types/node": "22"
  "@types/react": "19.0.0"
  "@types/react-dom": "19.0.0"
  date-fns: "4.1.0"
  dotenv-cli: "8.0.0"
  lucide-react: "0.513.0"
  next-themes: "0.4.4"
  next: "15.2.3"
  postcss: "8"
  react-dom: "19.0.0"
  react-hook-form: "7.57.0"
  react: "19.0.0"
  superjson: "2.2.2"
  tailwindcss: "4.1.8"
  typescript: "5.8.3"
  zod: "3.25.49"
